GET http://localhost:3000/api/usuarios

###

GET http://localhost:3000/api/usuarios/cuxvas@uv.uv

###

POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "email": "prueba@uv.mx",
    "password": "patito",
    "nombre": "Un nuevo usuario pato",
    "rol": "Administrador"
}

###

PUT http://localhost:3000/api/usuarios/prueba@uv.mx
Content-Type: application/json

{
    "email": "prueba@uv.mx",
    "nombre": "Usuario pato editado",
    "rol": "Usuario"
}

###

DELETE http://localhost:3000/api/usuarios/prueba@uv.mx

###

DELETE http://localhost:3000/api/usuarios/cuxvas@uv.uv
